### ISSUE TITLE
Покращення

### ISSUE THREAD

**Issue by Bibika** [maulitta/utm_checker#10]
1. Если количество параметров не совпадает, было бы круто, что бы в результатах подсвечивалась недостающая/лишняя часть.
2. Если какой-то из параметров не совпадает, что бы в результатах было примерно так:
   Ошибка: [параметр, в котором есть ошибка]
   Ожидаемый результат: [корректный параметр]

**Comment by maulitta** [comment]
1. Теперь для всех случаев, кроме полного совпадения, отображается ожидаемы и фактический список, а так же список того, что не соответствует.
2. Добавил текстовое описание того, что не соответствует.
   ![default](https://cloud.githubusercontent.com/assets/20155800/17644294/0beed6fa-618b-11e6-8c43-83d3baf11f61.PNG)
   ![_1](https://cloud.githubusercontent.com/assets/20155800/17644296/0befdf32-618b-11e6-9c65-97629f85bab0.PNG)
   ![2](https://cloud.githubusercontent.com/assets/20155800/17644295/0befdc12-618b-11e6-9628-2b2208f9d84c.PNG)
